filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /app/logs/grpc-server.log
  json.keys_under_root: true
  json.add_error_key: true

logging.level: debug
output.logstash:
  hosts: ["logstash:5044"] 